### ISSUE TITLE
시작하는 시점에서 드는 의문점 3가지

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#1]
system-monitor 의문점

1. 목표는 다솔관 PC 관리 시스템(<-system-monitor를 우리의 현실에서 와닿게 표현하기 위함.)
2. Diagram은 시간이 너무 많이걸려서 불필요하다라는 말씀 
  * 의문점1 : 요구사항 분석과 class, sequence에 대한 기획은 어느정도가 적당한가?
  * 의문점2 : 대쉬보드로 소통하는 것으로 diagram설계해서 대화하는것을 대체할 수 있는가?

3. ☆ 요구사항분석을 어떤식으로 할 것인가?

**Comment by serenity320** [comment]
## 의문점1

* Class에 국한하지 않고, 데이터 모델링을 한다 생각하자
    * OPP의 Class나 Database의 Table나 유사한...
    * 객체의 데이터(필드)와 기능(메서드) 정의
    * 객체간의 관계 정의 (ex. Process ID와 같은 유니크한 값 기준)
* 정형화된 Sequence보다는 객체간의 관계를 화살표 등으로 단간 표기
    * 디자인 패턴이 들어가면 좋을텐데...ㅎㅎ

## 의문점 2

* (!?)

### 요구사항 분석

* OS 혹은 Windows의 특징을 살펴보기
    * CPU
        * Usage
        * Process, Thread
    * Memory (RAM)
        * Usage
   * Storage (HDD, SDD)
        * Usage
    * Network
        * Traffic(Up/Down)
    * Etc..
* 부가적인 기능 살펴보기
    * 현재 활성화된 프로세스
    * 특정 프로그램 동작 여부
    * 원격 종료/재부팅
    * 화면공유 및 제어

**Comment by jongwuner** [comment]
2번에 의문점에 전제가 좀 많이 생략되어있어서 다시 작성합니다.
- 다이어그램을 만드는 이유는 팀원들끼리 기획에 대해 보다 원활하게 소통하기 위함이다.
- 다이어그램(usecase,class,sequential)을 만드는 것은 시간이 많이 소비된다.
-> 그러면 다이어그램을 만들지 않고, 팀원들과 기획에 대해 소통할 수 있는 수단은 무엇인가?
-> 그것이 깃헙 칸반보드(대쉬보드)인가? 칸반보드가 다이어그램제작을 대체 할 수 있는가?

최초에 의도한 질문입니다.

**Comment by jongwuner** [comment]
#### 칸반보드가 다이어그램을 대체할 수 있다.<br>

![image](https://user-images.githubusercontent.com/16419202/66097494-8dbabc00-e5d9-11e9-93eb-8d0b65a5eb8c.png)

**Comment by jongwuner** [comment]
![image](https://user-images.githubusercontent.com/16419202/68312879-0c35dc80-00f7-11ea-8466-41156b55b2e9.png)
