### ISSUE TITLE
GUI qt

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#10]
- qt GUI 기반 Client 설계중
  - `qt creator` 활용

**Comment by jongwuner** [comment]
## Installation & Hello World
![image](https://user-images.githubusercontent.com/16419202/67154211-3768af80-f333-11e9-9644-f83ffef8835f.png)

**Comment by jongwuner** [comment]
- Module별로 Button 생성
- Module별 Widget에다가 또 얻어야할 정보들 Button 생성

**Comment by jongwuner** [comment]
## In Progress (qt GUI)
![image](https://user-images.githubusercontent.com/16419202/67542542-33200600-f728-11e9-857e-5f79d4d46bbc.png)

- 추가적인 **모듈** 개발에 따른 항목별 **분류**는 실시간으로 이뤄져야 할 듯 하다.
- 모듈개발이 완성되면 버튼하나 **추가** -> **분류** 되는 과정으로 진행해볼 예정.

**Comment by jongwuner** [comment]
## To-do
- 디자인에 대해서 태클을 받지 않기 위해 **QT를 이쁘게** 만들 수 있는 방법을 한번 강구해보겠음.

**Comment by damin8** [comment]
디자인 부분에 대해서는 나중에 생각해봐도 될 거 같음

바쁘지 않다면 예쁘게 만들면 정말 좋겠지만

바쁘다면 급한건 아니라고 생각함!!!

**Comment by jongwuner** [comment]
@damin8 공감합니다.
@winterlood 동의하면 일단 이 Issue는 Close하려고 합니다.

**Comment by winterlood** [comment]
@jongwuner  디자인이 굳이 필요하지 않다는 생각이 크게듦

@damin8  의견에 공감하는 바

관리 관제 프로그램의 경우, 이쁘고 좋은 디자인보다는 ux에 더 초점을 맞추는 편이 좋지 않을까 고려

**Comment by jongwuner** [comment]
@winterlood 참고하겠음.
모듈 1개 단위 씩 개발을 할 때마다, `Android`, `Server`, `Client`의 **UI**를 **즉각 명세**하는게 좋아보임. 
그때마다 그리거나, 툴을 이용하기 보단(x)
간략한 스케치 정도로 진행하겠음.
@damin8
