### ISSUE TITLE
원격 종료 / 재부팅

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#11]

**Comment by winterlood** [comment]
원격종료 / 재부팅
===

1. H/W 요구 환경
===

환경 : Window 10 으로 가정

WOL 
---

(Wakeup-On-LAN)을 응용 해야 할 것으로 예상됨

WOL 이란, PC의 Network Card 에서, Wake up Frame 이 수신되는 것을 알아차리기 위해

Network를 지속적으로 감지함, (PC off 상황에도, Link 에 LED가 점등 되어있다고 함)

Wake Up Frame
---
간단하게, 수신 받은 해당 Frame이 Wake-up-Frame인지 아닌지 구분하는 핵심적인 요소로

**MAC주소가 16번 중단없이 반복된다** 

가 있음

그러나, MainBoard가 해당 Wake up Frame을 수신하여, WOL기술을 사용할 수 있도록 설계된 

CMOS와 H/W를 가지고 있어야 한다고 함.

> Pentium4 이상 AMD의 경우 AthlonXP이상의 PC는 대부분 WOL이 지원된다고 함 다행

2. BIOS 요구 환경
===

PC의 BIOS설정에서 WOL 기능을 Enable 해줘야 한다고 함.

CMOS Setup에서 쉽게 Enable로 토글해 줄 수 있는걸로 확인함, 

> Power Management Setup -> Wake-Up-by PCI Card : Enable or Power On by Ring or WOL : Enable


3. OS 요구 환경
===

Windows Driver를 설정해야 한다.

> 장치관리자 -> 네트워크 어댑터 -> [WOL 사용 LAN Card 명] -> 고급 -> 깨우기 or Wakeup On LAN<br> 
> 설정을 Magic Packet 발생시 깨우기로 설정

**Comment by jongwuner** [comment]
## 나의 의견
`WOL`을 사용하려면 우선적으로 L3에서 실험해야 한다. 그게 대표적으로 공유기.
결국 WOL을 이용하기 위한 전제조건은 `Cleint ~ Server`간에 **LAN**이 붙어있으면 된다. 
**결론 : L3에서 실험하자.**

## Ref. 
- 세상에서 제일쉽게 L1~L7까지 설명해놓은 포스팅 : https://one-ion.tistory.com/144
- WOL 설정방법 : https://post.naver.com/viewer/postView.nhn?volumeNo=9851246&memberNo=15864833

**Comment by jongwuner** [comment]
## 나의 의견 부연
우리는 세 파트로 나눈다. `Mobile(Android)`, `Server`, `Client(다솔관PC)`
- Mobile : 네트워크 A
- Server : 네트워크 B
- Client : 네트워크 C 
  - 이더넷 네트워크 으로 연결되어있다.(Layer 2)
  - ex. 128.13.255. 0 ~ 255 (게이트웨이 제외, 255개의 PC 사용가능)
   * 이더넷 네트워크의 규모에 따라 유동적으로 구성 가능.

**Comment by jongwuner** [comment]
## 생각해볼 점
- @winterlood 다른 이더넷의 ARP Table을 얻을 수 있는 방법은?

**Comment by jongwuner** [comment]
#15  Issue와 합쳐서 봐야할듯 합니다.! @winterlood

**Comment by winterlood** [comment]
제한 사항
---

CMOS 설정을 S/W 단에서 컨트롤 할 수 있는가 ???

**Comment by jongwuner** [comment]
`Registry` 가 뭔가 단서가 될 수도 있다.

**Comment by serenity320** [comment]
* COMS 설정을 운영체제에서 제어하기에는 어려움이 있음(할 수 없음..)
    * 제조사, 모델별로 방법이 너무 상이함
    * 커널 레벨 드라이버에서 제어해야 함
* 메인보드마다 WOL을 지원하는 여부가 다름 (특히 삼성, 레노버와 같은 제조사는 미지원)
* 하드웨어 영향이 있는 원격 실행보다 종료나 재부팅에 관한 기능을 특화시킬 필요가 있음

**Comment by jongwuner** [comment]
우선은 PC 1대 vs Mobile 1대로 실험하자.
그러고 나서 PC의 숫자를 늘려도 된다. 그냥 Clone일 뿐이라서.

**Comment by jongwuner** [comment]
#24
