### ISSUE TITLE
IsConnectedToServer

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#12]
- Traffic(Up / Down)

**Comment by damin8** [comment]
## Traffic

- 인터넷상에서 송수신 되는 모든 통신의 양

- 모든 파일이 들어오고 나가는 것

- 실시간으로 접속자 체크프로그램 사용 시 트래픽 과다 발생의 원인

- 대역폭이 높아야 동시접속자 많이 수용 가능

**Comment by jongwuner** [comment]
트래픽을 너무 어렵게 생각하지 말고, 
`Client ~ Server`간 구조 상에서 필요성을 먼저 따져보자.

**1. Client ~ Server가 통신이 현재 되고 있는 상황인지?**
2. 네트워크 상 어떠한 문제가 발생했을 때 실마리가 될 수 있지 않을까?
  - 동일한 Server와 복수의 Client간 성능비교.
  - ex. 1번 pc ping test 결과 1초, 2번 pc ping test 결과 5초

**3. Server와의 통신방식을 먼저 고려하고나서 자료수집을 할 필요도 있다.**
  - Http(★), Socket(★), Pipeline, Shared Memory etc.

**Comment by jongwuner** [comment]
> ## Traffic
> * 인터넷상에서 송수신 되는 모든 통신의 양
> * 모든 파일이 들어오고 나가는 것
> * 실시간으로 접속자 체크프로그램 사용 시 트래픽 과다 발생의 원인
> * 대역폭이 높아야 동시접속자 많이 수용 가능

1, 2번째 사항 의미있는 고민인 듯 함.

**Comment by jongwuner** [comment]
#15  Issue와 합쳐서 봐야할듯 합니다.! @winterlood

**Comment by damin8** [comment]
- Server와의 통신 방식

> 통신 방식을 정하고 나서, 그에 대한 자료 수집을 하고 싶다.

> 통신 방식을 정한다면, 통신이 현재 되고 있는 상태인지는 확인 쉽게 가능할 듯.

**Comment by jongwuner** [comment]
- Android에서 받아서, PC로 받아주는 Spring? Java ? 적합한가?

**Comment by jongwuner** [comment]
## Issue 이름 변경
- ~Network Traffic~ -> **IsConnected**

**Comment by damin8** [comment]
# Server

![image](https://user-images.githubusercontent.com/52910837/67951079-2458b800-fc2e-11e9-90eb-40b23bb7e99a.png)

1. Server만 켰을 때

Client가 들어올 때 까지 계속 대기중

![image](https://user-images.githubusercontent.com/52910837/67951136-45210d80-fc2e-11e9-9cf9-f9cd3ed34a14.png)

2. Client가 연결 시도

연결 Accept 후에 메시지 수신 및 발신

# Client



1. Client 실행

![image](https://user-images.githubusercontent.com/52910837/67951207-6aae1700-fc2e-11e9-89b4-ea2bc33334ec.png)

클라이언트 실행 시, 메시지 발신 및 수신

Code is [Here](https://github.com/22hours/system-monitor-study/tree/master/IsConnected/Code)

**Comment by jongwuner** [comment]
## Spring이 http여서, 통신방식이 수동적이지 않나?
- Android에서 Spring으로 요청
  - 이 때, Spring에서 C++로 요청이 가능한지 생각해봐야 한다.

**Comment by jongwuner** [comment]
#24

**Comment by damin8** [comment]
Spring으로  Socket 통신 하면 되는거 아닌가?

- Android에서 Spring으로 요청
- 이 때, Spring에서 C++로 요청 (Socket)

**Comment by damin8** [comment]
REST api 때문에 그런거라면 C++도 http 통신 되니까 문제 없을 듯!

**Comment by damin8** [comment]
Java를 이용해 Server와 Http 통신

Response가 왔다면, 통신이 된다는 뜻.
