### ISSUE TITLE
Alternative flow

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#14]
같이 얘기를 해보고 같이 정규화를 해야 하는 상황들

내가 생각한것이고, 더 추가가 무조건 될 것임.

Master 입장

1. 네트워크가 끊겼을 때,  Client의 컴퓨터를 어떻게 관리할건지

2. Client의 프로세스가 하나 이상 켜져 있더라도, 일정 시간 사용을 안하면 Client는 나간 것으로 판별하여 종료를 시킬텐데, 그 안에 중요 문서가 있다면?

3. Client의 프로세스가 하나 이상 켜져있고, 일정 시간 사용을 안하지만 그에 대해 발표나 회의를 하고 있다면?

2번과 3번은 비슷한 맥락

**Comment by jongwuner** [comment]
### 이에대한 나의 의견
> 1. 네트워크가 끊겼을 때, Client의 컴퓨터를 어떻게 관리할건지
** 너무나도 극단적인 상황설정일 수 있음@@**
일단 극단적인 상황설정이라 생각하는 이유는, 
1. 클라이언트는 어차피 네트워크가 끊길 경우, pc를 사용할 이유가 없음. 
2. 만약 추후에 사용하는 사람을 위해 네트워크를 끊고 해킹모듈을 설치하는 경우가 있을 수 있으니, 이것은 보안적인 측면에서 생각해봄직한 고민이긴 함.

! 네트워크 문제는 환경(다솔관 서버실)을 탓해야 하지 않을까!?!? 개발자로서 어쩔수 없는 상황인것같아 보이긴 하는데, 개발자 된 도리로서 같이 고민해봄직하다고는 생각한다... 

> 2.Client의 프로세스가 하나 이상 켜져 있더라도, 일정 시간 사용을 안하면 Client는 나간 것으로 판별> 하여 종료를 시킬텐데, 그 안에 중요 문서가 있다면?

사용자 use-case로 '연장신청/야간사용신청'을 만들어두면 간단히 해결된다. 그러면 시스템은 인지하고 자동종료를 하지 않겠다. '신청'을 안한 사용자의 잘못이 되는 것. 추후에는 사용자들간의 문화와 습관이 자리잡아야 하는 문제.

>3.Client의 프로세스가 하나 이상 켜져있고, 일정 시간 사용을 안하지만 그에 대해 발표나 회의를 하>고 있다면?

2번과 마찬가지

**Comment by damin8** [comment]
###A1

극단적인 상황이란 말에 많은 공감

> 1. 클라이언트는 어차피 네트워크가 끊길 경우, pc를 사용할 이유가 없음.

이 부분에 대해서 Client가 PowerPoint or Word 등 네트워크가 필요 없는 문서 작성 등등을 할 수도 있다고 생각함.

> 만약 추후에 사용하는 사람을 위해 네트워크를 끊고 해킹모듈을 설치하는 경우가 있을 수 있으니, 이것은 보안적인 측면에서 생각해봄직한 고민이긴 함. 

이 부분도 차차 생각 해봐야 될 거 같음.

이 부분은 시원하게 풀리지는 않았다..

계속해서 생각해 보겠습니다

###A2

너무 공감하고, 너무 좋은 답변이라고 생각함.

**Comment by damin8** [comment]
- 네트워크 끊김 생각 x

> 인지하고 상황 가정하지 않겠습니다.

- 리서치 후에 생각한다.

> Backlog에 올림

**Comment by damin8** [comment]
1. 네트워크가 끊겼을 때는 생각 안하는 걸로

2. 일정 시간 사용 안함 -> 종료 예약 시간으로 변경

-> 따라서 사용자는 중요한게 있다면, 종료 연장 신청을 할 것임.

3. 2번과 동일
