### ISSUE TITLE
Android GUI

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#18]
- 개발언어, 환경 research

**Comment by winterlood** [comment]
HelloWorld
===

개발환경
---

Tool : Android Studio
Language : Kotlin

![](./module/GUI(Android)/img/helloworld.JPG)

**Comment by jongwuner** [comment]
good~~ 3일간의 느낀점도 써주세요 @winterlood 
이를 바탕으로, 앞날에 대한 계획도

**Comment by jongwuner** [comment]
> 정환이 그거 `Android UI` 뼈대는 다 해결되지 않음?
<sub>[View in Slack](https://22hoursworkspace.slack.com/archives/CSA7VKFNH/p1578658162012100)</sub>

**Comment by jongwuner** [comment]
> 응 뼈대는 다 나왔어
<sub>[View in Slack](https://22hoursworkspace.slack.com/archives/CSA7VKFNH/p1578658180012500)</sub>

**Comment by jongwuner** [comment]
> 현재 카드뷰사용하는데 런타임 에러가 나서 해결중
<sub>[View in Slack](https://22hoursworkspace.slack.com/archives/CSA7VKFNH/p1578658196013600)</sub>
