### ISSUE TITLE
강의실 별 PC 분류

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#21]
- 강의실 별로 PC 분류를 해놓으면 편하지 않을까
- Ex) D404 의 PC들, D405 의 PC들

**Comment by jongwuner** [comment]
- Grouping 이라는 개념이 필요하겠네.
  - Server입장에서 도입해야하는 Group이려나?
  - *Ex.* Group dasol401, Group dasol402

**Comment by serenity320** [comment]
* 네트워크에서는 단말(PC)을 Node라고 표현 함
* 적어도 1회 PC에서 셋팅할 것을 고려해야 함
    * 회사라 생각하고 D401은 A팀, D402는 B팀 그리고 A팀의 소속된 팀원(Node)

**Comment by damin8** [comment]
@jongwuner Grouping 개념 필요할 듯

Server 입장에서 도입해야 한다고 생각함

Server에서 처음 세팅에서 Grouping을 하고, 그 다음부터 Group 별로 관리

각 강의실 별로 우리가 임의적으로 번호를 정해줘서 1번 Node, 2번 Node ... etc

이런 식으로 번호 정해주는 것도 나쁘지 않다고 생각함

Ex) D401의 3번 Node 종료

@serenity320 감사합니다!

**Comment by jongwuner** [comment]
#24 참조하여, 모듈제작 할 것.

**Comment by jongwuner** [comment]
**Group key** 를 사용하여 label 개념으로 붙일 생각임.

**Comment by damin8** [comment]
Server에서 Group key 사용하여 분류

이 부분에 대해서 에러 사항이 있다면, 차후에 얘기.
