### ISSUE TITLE
REST-API Construction

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#24]
![image](https://user-images.githubusercontent.com/16419202/68312879-0c35dc80-00f7-11ea-8466-41156b55b2e9.png)

**Comment by jongwuner** [comment]
### C++ REST SDK 가 상당히 난해
- Java Swing으로 `appache http`를 통해 구현하면 좀더 나을 수도

**Comment by damin8** [comment]
C++ REST SDK

C++ 코드에서 Microsoft의 클라우드 이용하는데 필요한 클라이언트, 서버 등등 작업등에 대한 기능을 제공

+ 윈도우 뿐만이 아닌, ios, 리눅스 등등 이질적인 운영체제 상에서도 동작하거나 개발할 수 있도록 크로스 컴파일 가능

C++ REST SDK를 이용해 HTTP을 이용한 서버 애플리케이션과 클라이언트 애플리케이션을 쉽게 만들어 낼 수 있다. 

Reference

[REST SDK](http://blog.naver.com/PostView.nhn?blogId=drvoss&logNo=220340563782)

**Comment by jongwuner** [comment]
## Ver 1.1 
![image](https://user-images.githubusercontent.com/16419202/71482725-69245800-2847-11ea-8e4c-627b02f80d17.png)

## 참고사항
- GET : 롱 폴링기법 검토 중(제한 시, 일반 폴링기법 사용예정)
- POST : REST-API 상에서 PUT처럼 사용할 예정('생성'보단 '수정') 

## Reference
- [롱 폴링기법 (1) ](https://kamang-it.tistory.com/entry/Webhttp%ED%86%B5%EC%8B%A0%EC%9D%84-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EC%96%91%EB%B0%A9%ED%96%A5-%ED%86%B5%EC%8B%A0%EA%B8%B0%EB%B2%95-long-polling)
![image](https://user-images.githubusercontent.com/16419202/71482758-996bf680-2847-11ea-9a28-54f44e664655.png)

**Comment by jongwuner** [comment]
# 토요일 쯤을 목표로 서버구조 완성입니다.

## Server 멤버변수, 멤버메소드

```java
class PC{
private:
  bool power_status;
  int cpu_data;
  int ram_data;
     ...
public:
  PC(){}
     ...
}
```
## Android 해줘야 하는 것.(REST Call)
- POST Call 메소드
  ex) 
  https://system-monitor/pc/{i}/power/0
- GET Call 메소드
  https://system-monitor/pc/{i}/cpudata
  https://system-monitor/pc/{i}/ramdata
  

## Swing 해줘야 하는 것(REST Call)
- POST Call 메소드
  ex)
    https://system-monitor/pc/{i}/power/1
    https://system-monitor/pc/{i}/cpudata
    https://system-monitor/pc/{i}/ramdata
- GET Call 메소드
    https://system-monitor/pc/{i}/power

**Comment by jongwuner** [comment]
## 기본적인 GET 설계
![image](https://user-images.githubusercontent.com/16419202/71620276-68efd800-2c0c-11ea-9219-fc1f2eb2368a.png)
![image](https://user-images.githubusercontent.com/16419202/71620279-6e4d2280-2c0c-11ea-98df-f43039c14cab.png)
