### ISSUE TITLE
창업 동아리

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#25]
### 운영 목표

- 우수 창업 아이디어 발굴 및 육성
- 창업 교과목/캡스톤디자인과 연계를 통한 창업동아리 발굴 및 육성
- 대학 전반의 창업분위기 확산 및 창업 마인드 함양
- 사업화 아이디어의 구체화를 통한 실천창업자 양성

### 지원 내용

- 창업 동아리 발탁 되면 링크 사업단에서 지원해주는 내용

STEP 01

#### 창업교육

- 창업 강좌
- 캡스톤디자인
- 글로벌창의인재과정
- 창업캠프

STEP 02

#### 창업동아리지원
- 운영비지원
- 내/외부 창업경진대회 지원
- 창업멘토링

STEP 03

#### 실전사업화지원

-시제품개발지원
-지식재산권취득지원
-창업실무과정지원
-창업심화멘토링

STEP04

#### 창업지원

- 창업LAB 입주
- 사업자등록지원
- 기타 정부지원사업 연계지원
- 창업보육센터 입주 연계지원

### 참여대상

- 창업 아이템을 보유한 대학생(원) 재학(휴학)생
- 창업동아리 회원 수 최소 3인 이상 팀 단위로 신청

### 신청 방법

- 매년 3월 전체 공개모집
- 가톨릭대학교 공지사항 또는 LINC+ 사업단 홈페이지 참조
~~~
공개 모집 외에 참신한 창업아이템을 보유한 창업 동아리를 수시 모집하오니, 관심 있는 학생들은 창업 대학운영팀을 방문 후 상담 바람
~~~

### 문의처

구)02-2164-4734

## 전화해서 알아 본 내용

현재 가톨릭대학교에서 창업 동아리는 20개 이상이라고 함.

창업 동아리에도 등급이 있는데(일반, 심화)

매년 여름방학때 심사 후에 갈린다고 함.

문의처 전화번호가 바꼈다고 함 (02-2164-4734)

공개 모집 외에 참신한 창업아이템을 보유한 창업 동아리를 수시 모집한다고 해서 물어보니 방문하면 된다고 함.

**Comment by jongwuner** [comment]
`Google Drive / 2.Docs` 에 저장해둬서 Close
