### ISSUE TITLE
json 중복키 발생

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#30]
slack test겸 현재 상황

**Comment by jongwuner** [comment]
![image](https://user-images.githubusercontent.com/16419202/72151944-ef669f80-33ec-11ea-8cf6-5355c02280a7.png)

**Comment by jongwuner** [comment]
언더바가 찍히는 동일한 key가 동일한 value를 가지고 저장이 됩니다. 
사소한 문제겠죠 하하

**Comment by damin8** [comment]
만약 이 에러가 안고쳐 진다면, Client에서 받는 것을 정제해서 받을 수 있긴 합니다.

**Comment by jongwuner** [comment]
@damin8  일단 그렇게 해주길 바라오

**Comment by jongwuner** [comment]
![image](https://user-images.githubusercontent.com/16419202/72445549-38f02980-37f5-11ea-9061-db0530243d2a.png)

**Comment by jongwuner** [comment]
Solved
