### ISSUE TITLE
git release

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#42]
git clone tag가 잘안되는 듯. @damin8

**Comment by jongwuner** [comment]
Docker 도입 예정

**Comment by damin8** [comment]
Doker 확인 해보겠습니다

**Comment by jongwuner** [comment]
#49 
`wget` 써보세요. 확인부탁.

**Comment by damin8** [comment]
![image](https://user-images.githubusercontent.com/52910837/73277062-fa169680-422c-11ea-999d-a27c09bfebd3.png)

- 이렇게 뜹니다.

**Comment by damin8** [comment]
git clone tag 완료

wget -P 로 받아집니다.

Close 할게요

**Comment by damin8** [comment]
![image](https://user-images.githubusercontent.com/52910837/73278071-62b24300-422e-11ea-93d6-70493f65c402.png)

**Comment by jongwuner** [comment]
> `wget -P "<https://github.com/22hours/system-monitor-study/releases/tag/v1.2.1/system_monitor_ver1.2.1-SNAPSHOT.war>"`
<sub>[View in Slack](https://22hoursdev.slack.com/archives/CSA7VKFNH/p1580228087034600)</sub>
