### ISSUE TITLE
response time chnage (연장신청 모듈)

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#43]
PC Client쪽에서 문제가 될텐데, (물론 Android도 맞물림)
연장신청 모듈은 response time을 변경해야하는 소요가 생긴다.

**Comment by jongwuner** [comment]
## 생각하고 있는 방향 (Scenario)
1. request 대기중인 상황에서, response 시간을 변경해야 하는 소요.
2. 시간변경 event 발생
3. 즉시 response (**JSON**에서 `"powerStatus" : "ON"` 으로 반환)
4. client측에서 변경된 시간으로 다시 request

**Comment by damin8** [comment]
Scenario가 잘 이해가 안가서 그러는데

PC Client -> Server

1. ***나 언제 꺼?*** 를 이미 보낸 상태.

2. PC Client User가 연장신청

3. 그럼 PC Client Request(1회성)를 보냄

4. 결과적으로 Server -> PC Client로 보내야 하는 Response Time이 바뀐다.

여기서

Server -> PC Client (끄는 long polling) 이 문제가 된다는 거야?

PC Client가 연장이 된지 알아야 하기 때문에?

**Comment by damin8** [comment]
추가로

n 개의 long polling
n 개의 1회성 request
n 개의 일반 폴링

에 대해서 용어를 정해 놓는 것도 좋을 것 같음!!

ex) Server -> PC 연장신청 1회성 = Extension 1

**Comment by jongwuner** [comment]
N개가 무슨뜻임? PC n개라는건가

**Comment by jongwuner** [comment]
당장은 N개가 불가능. 스레드풀 만들어야함

**Comment by jongwuner** [comment]
비동기식 접근도 고려해야하고,
지금은 1대 1

용어 혼동안줄게

**Comment by damin8** [comment]
n개를 말한 거는

지금 당장이 아니라

나중에 생길 추가적인 기능에 대비 하자는 뜻!!

---

위에 내가 이해한게 맞나요?

**Comment by jongwuner** [comment]
ㅇㅇ
