### ISSUE TITLE
(Mobile) PC가 새로 켜질 때, mobile에 켜진 PC 반영해야 한다.

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#44]
## 문제상황
어플이 먼저 켜진상태에서, 새로 PC가 켜지면, json-type을 jsonArray-type에 추가하는 느낌으로

## (Common) Json-type
![image](https://user-images.githubusercontent.com/16419202/73150302-0f92a000-4109-11ea-983e-6744fba48819.png)

## (Mobile) JsonArray-type [어플이 최초 켜질 때, (1회성) ]
![image](https://user-images.githubusercontent.com/16419202/73150283-eb36c380-4108-11ea-8e99-64905d4e3584.png)

**Comment by jongwuner** [comment]
reference. [구글 독스](https://docs.google.com/document/d/1MOLwwLuQMRzMydqZNz7u6w7raaXkN3gsptwdGWn4_do/edit?usp=sharing)

**Comment by winterlood** [comment]
실질적인 TEST후 Issue close 하겠음

**Comment by jongwuner** [comment]
정환이랑 얘기더해봐야 하긴하는데,
내가 지금까지 생각하고 있는 바로는, 

Redis DB에
PC가 N대(ex. 가톨릭대학교 PC가 1000대) 있을 때, 어플 키면 O(N)탐색은 무조건 이뤄져야함.
그리고, 어플로 가져오는 PC는 `"powerStatus" : "ON"` 인 PC들만! 

어플이 켜져있는 상태에서는 롱폴링으로, (PC가 켜지는, PC client측에서 post 던지는 이벤트에 반응하는), 켜지는 PC의 `"powerStatus" : "ON"`로 변경. **PC가 꺼질때도 Post를 던져** `"powerStatus":"OFF"`로 변경.

**Comment by jongwuner** [comment]
우리에게 최악의 N size는 1000대라고 가정하기 때문에, 그렇게 크지 않다는 점을 생각하자.
심지어 이건 알고리즘 문제풀이도 아니고, 모든 문제해결을 1초만에 해야하는 것도 아니다.

**Comment by jongwuner** [comment]
v2.1에 반영완료, Mobile Client에 JSON 받는 method 추가해야해요

**Comment by jongwuner** [comment]
서버기준 `v2.3.8` 일반폴링으로 일단 진행중
