### ISSUE TITLE
(Server <-> Android) "~/mobile/pc" GET 요청 시 pcs 변수 값 오류 

### ISSUE THREAD

**Issue by winterlood** [22hours/system-monitor-study#45]
![image](https://user-images.githubusercontent.com/46296754/73253195-637fb080-41ff-11ea-87fe-8b1a753ac978.png)

> 다음과 같이 mobile용 전체 pc 정보 GET 요청시 pcs 배열에 null 값만 옴

![image](https://user-images.githubusercontent.com/46296754/73253239-785c4400-41ff-11ea-91f0-47756c1c4710.png)

> 그러나 다음과 같이 pc의 id를 정확하게 입력하여 GET 요청시 기록된 정보가 존재

@jongwuner @damin8

**Comment by jongwuner** [comment]
redis open 코드가 누락되어있음. 바로 해결가능.

**Comment by jongwuner** [comment]
![image](https://user-images.githubusercontent.com/16419202/73274708-58da1100-4229-11ea-814f-1bca7694bf23.png)

- v1.2.1 로 01.29 00시에 업로드.
