### ISSUE TITLE
PC켜질때, 언제꺼요? About Long Polling

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#46]
PC Client -> Server

Post Long Polling (나 언제 꺼요?)

Request (PC Client -> Server)

- 모든 필드 보내기
- Response 기다리기

여기서 Response가 늦게(Server 가 잡고 있어서) 와야 하는데

바로 response가 온다.

~~~
Response : {"timestamp":"2020-01-28T10:00:11.849+0000","status":404,"error":"Not Found","message":"No message available","path":"/pc/34_E1_2D_3C_81_E7"}
~~~

즉, Response를 잡지 못하고 있다.

**Comment by jongwuner** [comment]
response 시간만 늦추면 해결된다.

**Comment by jongwuner** [comment]
v1.2.1에서 해결

**Comment by jongwuner** [comment]
![image](https://user-images.githubusercontent.com/16419202/73276883-bae84580-422c-11ea-9684-d18d72dc6bd2.png)

- @damin8 어제 말했던, 해당 id의 모든 value는 반환은 받으나, android쪽 모듈진행되면, 여기에다가 이어붙일 예정.

**Comment by jongwuner** [comment]
- pc id
- 어플이 켜지는 순서와 pc가 켜지는 순서의 관계를 어떤식으로

- pc들이 켜져있고, 어플이 켜질때, 
 (server, mobile) 1000대를 모두 조사해서 powerStastus = ON애들을 다 가져온다.

- 어플이 먼저켜져있을 때, pc가 추가 켜진다.
 (Mobile) longpolling get 으로 대기를 한 상태에서, pc가 켜질때, get을 해온다.
 (PC) 켜질때, 언제꺼요? post날려줄때, to send Android pc의 모든 정보를 mobile로 보내준다.

- 어플이 켜져있을때, pc가 종료된다.
 (PC) 언제꺼요?에서 longpolling 'response'할 때,(종료예약시간이 되엇을떄) 끌꺼아냐.  
 (Mobile) PC longpolling response를 이벤트로 걸어서, 저게 발생하면, 해당 id를 인스턴스 삭제. 그리고 UI에서는 껏다는 표시. 
 (Server) DB에 powerStastus = OFF

**Comment by jongwuner** [comment]
#### 1 pc classId랑 pc Id
- (mobile) 강의실분류를 어떤식으로, class
  
   HashMap<String, ArrayList<Pc>> map 
   map[D401] = {id1, id2, id3, }

- 
  다민이랑 나랑 걱정하던 것. 
  classId를 없애자라는 의견이 나왔다. -> N = 1000이기때문에 괜찮다라는 생각.
  for( if(classId == D401) ) O(N).  


- 신다민이 걱정하는 것은
  우리가 1000대에 PC에 client를 설치를 한다. 아키텍처에 등록을 하기위해, 
  그러면, pcId와 classId를 부여를 해야 하는데, 그것을 일일이 부여해야할까?
  
  이 pc에 앉아서, 그래너는 id : 10011이고, classId : D405다 이런식으로 일일이 노동을 해야하느냐?
  client를 깔아두면, 어떤 코드에 의해서, mac를 불러오는 함수를 실행시켜서, 그것을 id로 배치하고, 
  그 id에 따른 규칙으로 classId를 뽑아낼수 잇지 않을까?

  -> mac주소로는 절대 안되고, 다른 대안이 있을까? 
  -> 예를들면, PC계정명 및 
  -> 규칙이 있는 무언가를 찾자.
  -> winAPI 함수?
