### ISSUE TITLE
PC Client -> Server Request 종류 명시

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#47]
# Request 종류

### Mesaage channel (Long Polling)

~~~
URL = http://13.125.225.221/pc/{id}/message/{minute}
~~~

---

# Post

### PC Shutdown (Long Polling)
-> `v1.2.1` General Polling으로 구현되어있음.

**처음에 접속하자 마자**

classId, powerStatus, id, name, cpuData, ramData, startTime, endTime 보내주기

~~~
URL = http://13.125.225.221/pc/{id}/power/{endTime}
~~~

---

### PC Extension (One-time)

id와 endTime보내주기

ex) {id : 홍길동, endTime : 2010-02-56-21-39}

~~~
URL = http://13.125.225.221/pc/{id}/power/{endTime}
~~~

---

### PC Update (General Polling)

id와 cpuData, ramData 보내주기

ex) {id : 홍길동, cpuData : 77.23, ramData : 31.45}

~~~
URL = http://13.125.225.221/pc/{id}/data
~~~

---

# Response 종류

## Get

id 와 msg 받기

ex) {id : 홍길동, msg : 2분남았습니다. 자료 정리 서둘러라.}

PC 연장신청을 대비해서

msg가 null 값이 들어오는 경우 대비

---

### PC Shutdown (Long Polling)

id와 powerStatus 받기

ex) {id : 홍길동, powerStatus : OFF} 
*ON / OFF 대문자

PC 연장신청을 대비해서

powerStatus가 ON이 오는 경우 대비

---

### PC Extension(One-time)

- 필요 없다.

---

###  PC Update(General Polling)

- 필요 없다.

**Comment by jongwuner** [comment]
게시글 제목만 봐도 내용유추되게끔 작성좀부탁하겠음 .

**Comment by damin8** [comment]
네 알겠습니다

게시글 제목만 봐도 내용 유추 되게끔 작성

확인이요

**Comment by jongwuner** [comment]
어제 확인하고 수정해논겁니다

**Comment by jongwuner** [comment]
v3.5.0 기준 docs에도 명시되어있어 Close합니다.
