### ISSUE TITLE
PC 변수

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#48]
![image](https://user-images.githubusercontent.com/52910837/73256634-9b89f200-4205-11ea-82a4-098df3c21282.png)

ramData, startTime, endTime이 안들어가는 현상

**Comment by jongwuner** [comment]
아키텍처에 필요하지 않은 Rest여서 뺐는데, 
Test용으로 다시 넣었습니다.
안들어가졌던 현상은 해시도입 전후로 나뉘어서 그렇슴.
`v1.2.1`
