### ISSUE TITLE
PC, Mobile Long-Polling Response (무한 Request상태)

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#51]
서버 ON 후, 최초 몇 회는 정상적으로 반환했는데, 그 이후에 반복 실행에는 response가 올바르지 않은 것 같다. java Timer class에서 비슷한 문제가 식별된 적 있는데, 테스트 해보고 개선하겠음.

@Damin @winterlood

**Comment by jongwuner** [comment]
추측되는 원인으로
- 리눅스 서버 시간동기화 문제
- Java Timer class 활용의 문제
- 롱 폴링 자주 호출했을 때 발생하는 내가 인지못하고 있는 문제.

**Comment by damin8** [comment]
![image](https://user-images.githubusercontent.com/52910837/73427793-f3963500-437a-11ea-82e4-d5423d840339.png)

약 9시간 정도 차이나는 거 같음

**Comment by damin8** [comment]
![image](https://user-images.githubusercontent.com/52910837/73427944-3e17b180-437b-11ea-81d7-208613a71532.png)

aws 시간은 서울로 되어 있는데 우분투는 왜 07시지?

**Comment by jongwuner** [comment]
개별 인스턴스마다 별개의 컴퓨터니까 상관없을 수 있지

**Comment by damin8** [comment]
![image](https://user-images.githubusercontent.com/52910837/73428676-25a89680-437d-11ea-9b13-2f4bbb26c30f.png)

시간 변경 완료
