### ISSUE TITLE
instance not same (@pathvariable id != Json의 id)

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#52]
![image](https://user-images.githubusercontent.com/16419202/73361570-8a65e180-42e8-11ea-9f9c-35234089bda0.png)

## 드래그해놓은 id와, URL상의 id가 다르다!

이렇게 해도 지금 정상적인 입력이 진행되는데, 
혼동이 올까봐 이 부분은 이 현상이 못일어나게 수정하겠음.

**Comment by damin8** [comment]
무슨 말인지 잘 모르겠습니다 ㅠ

**Comment by jongwuner** [comment]
드래그해놓은 id와, URL상의 id가 다를 수가 있다는 말!

**Comment by jongwuner** [comment]
client분들이 명확하게 규약을 지켜주셔야 함!
