### ISSUE TITLE
GET : `~/mobile/pc/` 에서 'n' 식별

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#53]
## 22hours 서버 상
![image](https://user-images.githubusercontent.com/16419202/73361890-30195080-42e9-11ea-93cc-2efdfdcfc763.png)

- **'n'** 이 식별됨.

## 로컬 환경 상
![image](https://user-images.githubusercontent.com/16419202/73361794-04966600-42e9-11ea-8c8a-8662d38db732.png)

- **'n'** 이 식별되지 않음.

-------------
추측되는 원인으로는, 
json 반환결과를 보기좋게 정렬하려고  , "\r\n" 을 넣는데, 
그것의 부작용인 것 같다.  UTF-8, encoding 코드가 있는데, 요게 호환문제가 있으려나? 
json 자체를 반환하는 목적의 측면에서는 해결하는데 큰 어려움은 없다.

@winterlood

**Comment by winterlood** [comment]
현재 Android 상에서,
~~~
"pcs" : [
 {...},
{...}
]
~~~
위 처럼 정상인 pcs array는 처리 가능 그러나

~~~
"pcs" : [
null,
null,
 {...},
{...}
]
~~~

위와 같이 null값을 포함하는 array 를 처리하지 못하고 있어 수정중

**Comment by jongwuner** [comment]
원인한번 찾아볼게요

**Comment by jongwuner** [comment]
# Solved 

![Uploading image.png…]()
