### ISSUE TITLE
클라이언트 개발 용이하게끔 하기 위해 모든 restful method에 response 붙여드리겠습니다.

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#54]
response가 no message 이런게 떠서 혼동이 오는 것 같은데, 

response가 필요없는 호출에 한해서는 아무것도 반환을 하지 않아서 그렇습니다.

대략적으로라도 response를 하는 것으로 수정해나가겠습니다.

**Comment by damin8** [comment]
이 부분에 대해서는 혼동보다는

잡고 있어야 된다고 생각했던 request의 response가 너무 빨리와서 사진 올리고 에러 뜬다고 말했던 것!

**Comment by jongwuner** [comment]
오키오키, 그럼에도 불구하고 필요성을 느꼈습니다.

**Comment by winterlood** [comment]
너무 좋은 의견입니다 대 찬성입니다

**Comment by jongwuner** [comment]
반영하겟소

**Comment by jongwuner** [comment]
`v1.2.8`에 반영하였습니다. 바로 테스트가능이요.
