### ISSUE TITLE
Version 2 설계의 필요한 모든 것 A to Z

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#56]
#### 2 어플이 켜지는 순서와 pc가 켜지는 순서의 관계를 어떤식으로

- pc들이 켜져있고, 어플이 켜질때, 
 (Server, Mobile) 1000대를 모두 조사해서 powerStastus = ON애들을 다 가져온다.

- 어플이 먼저켜져있을 때, pc가 추가 켜진다.
 (Mobile) longpolling get 으로 대기를 한 상태에서, pc가 켜질때, get을 해온다.
 (PC) 켜질때, 언제꺼요? post날려줄때, to send Android pc의 모든 정보를 mobile로 보내준다.

- 어플이 켜져있을때, pc가 종료된다.
 (PC) 언제꺼요?에서 longpolling 'response'할 때,(종료예약시간이 되엇을떄) 끌꺼아냐.  
 (Mobile) PC longpolling response를 이벤트로 걸어서, 저게 발생하면, 해당 id를 인스턴스 삭제. 그리고 UI에서는 껏다는 표시. 
 (Server) DB에 powerStastus = OFF

- pc를 사용자가 임의로 종료시켜버린다.
-> 아이디어 1 : (종원) pc로부터 general polling(id, cpuData, ramData) 이 일정시간동안 동작하지 않으면, PC는 먼저 껴저버린 것으로 판단. 
-> 아이디어 2 : (다민) 종료할때, shutdown hook으로 post를 보낸다. request : "나 갑자기 지금꺼요~"
-> 아이디어 3 : (지금 현 상태) 종료시간이 안되었는데, 그냥 pc꺼져있지만, pc가 켜져있다고 서버에서 인지하고있는 것. 
	       (PC방 카운터프로그램도 켜져있다고 인지하니깐, 사용시간이 남아있으면, )

**Comment by jongwuner** [comment]
#1 pc classId랑 pc Id
- (mobile) 강의실분류를 어떤식으로, class
  
   HashMap<String, ArrayList<Pc>> map 
   map[D401] = {id1, id2, id3, }

- 
  다민이랑 나랑 걱정하던 것. 
  classId를 없애자라는 의견이 나왔다. -> N = 1000이기때문에 괜찮다라는 생각.
  for( if(classId == D401) ) O(N).  


- 신다민이 걱정하는 것은
  우리가 1000대에 PC에 client를 설치를 한다. 아키텍처에 등록을 하기위해, 
  그러면, pcId와 classId를 부여를 해야 하는데, 그것을 일일이 부여해야할까?
  
  이 pc에 앉아서, 그래너는 id : 10011이고, classId : D405다 이런식으로 일일이 노동을 해야하느냐?
  client를 깔아두면, 어떤 코드에 의해서, mac를 불러오는 함수를 실행시켜서, 그것을 id로 배치하고, 
  그 id에 따른 규칙으로 classId를 뽑아낼수 잇지 않을까?

  -> mac주소로는 절대 안되고, 다른 대안이 있을까? 
  -> 예를들면, PC계정명 및 
  -> 규칙이 있는 무언가를 찾자.
  -> winAPI 함수?

**Comment by jongwuner** [comment]
- 사용자마다 계정이 나뉘어져있는가?
- 시스템모니터를 로그인할 때, 개인 계정 비번을 입력을 하는가? -> name은 유효하고. 
- 아니면 강의실의 '5번pc로 id와 classid' 는 뭐 고정인가? -> 'name'은 필요없을수도 있지.  
- 관리자는필요하다. 경비아저씨는 여럿명. 
- 교수님들한테 관리자를 준다면, ? -> 'PC admin Client' V3, V4. 
- 사용자가 계정을 주면, 다른 사람들은 pc를 사용할 수 없다.
- 로그인, V2.

**Comment by jongwuner** [comment]
@damin8 @winterlood PC, Mobile 로그인에 대한 의견개진이 필요.

**Comment by winterlood** [comment]
어플,pc,서버의 연결고리에 대해
---
아이디어 2 : (다민) 종료할때, shutdown hook으로 post를 보낸다. request : "나 갑자기 지금꺼요~

위 아이디어로 채택된것으로 생각하겠슴

PC ClassId에 대해
---

제일 먼저 해봐야 할 것은,
다민이랑 내가 다솔관 강의실 별 PC 내부 User 정보들에 차이점이 존재하는지 알아봐야 할 듯
분명히 무언가는 존재할 것이라고 생각하고, 
코로나 사태가 잠잠해지고, 학교의 폐쇄조치가 해제되면 바로 달려가서 해볼 계획임


로그인에 대하여
---
정말 더 나아가서 생각해보자면,
즉 우리가 더욱더 완벽한 서비스를 지향하게 된다면,
학교 PC를 사용하는 어떤 한 일반인의 입장에서,
어떤 관리자가 언제 어떤 PC를 종료하였는지에 대한 로그가 서버에 있어야 된다고 생각
이는, 건물 내 CCTV와 비슷한 논리라고 생각 됨
그러므로 개인을 식별할 수 있는 ID와 PW가 존재하는
로그인은 필요하다고 생각함

추가적으로,
Android상에서 View는 이미 준비되어 있으므로 (디자인과 구현까지 마친 상태)
기능 추가에 대한 부담은 전혀 없다.

**Comment by jongwuner** [comment]
첫번째 두번째사항 확인했고, 세번째사항 동의함

**Comment by damin8** [comment]
로그인으로 하면

우리학교로 예를 들자면

하꼬에서 일하는 사람(ex. 경비아저씨)의 관리자 아이디가 있는거지?

학생들은 없고??

만약 이게 맞다면

학교에서 일하는 사람인지 인증? 이 필요할 거 같음

+

만약 인증이 필요없다면 그 사람들에게만 아이디를 나눠 주는 식? (회원 가입 없이)

아니면 관리자 아이디 비밀번호를 1개만 두고 

학교에서 일 하는 사람들에게만 뿌리는 식?

**Comment by jongwuner** [comment]
Pc 클라이언트도 고유의 ID가 필요

**Comment by jongwuner** [comment]
학교일하는 사람한텐 개인계정 혹은 1개의 admin계정이 필요(Mobile)

**Comment by damin8** [comment]
Admin 아이디어는 좋은데

클라이언트의 고유 ID라는게

1. 학생들의 개별 로그인 용 아이디인지?

2. 아니면 그 맥주소 or 학교 컴퓨터 유사성 검사해서 pc 아이디라는 건지?

1번이라면 학생들이 다 가입하기에는 무리? 가 있지 않을까 싶음

**Comment by jongwuner** [comment]
2번이죠 2번으로 가기로 햇음

**Comment by jongwuner** [comment]
현재는 버전 v3.0을 달리고 있음.
