### ISSUE TITLE
PC 사용자가 PC를 자의적으로 끌 때

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#59]
## 사용자가 컴퓨터를 끌 때 

1. 우리 프로그램도 꺼질 것임.

2. 우리 프로그램 꺼질 때 Post로 Server에게 id랑 powerStatus를 준다.

> ex) {id : 홍길동, powerStatus : OFF}

3. One-time

## 사용자가 우리 프로그램을 끌 때

1. 컴퓨터를 끌 때와 똑같다.

2. 왜? 어차피 우리 프로그램을 사용하지 않으면, 서비스로 등록하지 않는 이상 우리는 아무것도 알 수가 없다.

3. 따라서 우리 프로그램 종로 = powerStatus = OFF 랑 같다고 취급
---
- 사용자가 PC를 자의적으로 끄거나 프로그램 종료할 때를 생각해봤는데 이렇게 하면 어떨까 싶어서

- Server와 얘기를 해야 하는 것이라서 

- @jongwuner 어떻게 생각하십니까

**Comment by damin8** [comment]
만약 괜찮다면 URL 설정해서 말씀 부탁드립니다

**Comment by jongwuner** [comment]
일단, PC방의 컨셉처럼, 사용시간이 남아있는데도 꺼진다면 그냥 켜져있는 것으로 간주하기로 마지막회의때 결정했던 것 같습니다. 제말이 맞나영??

**Comment by jongwuner** [comment]
@damin8

**Comment by damin8** [comment]
잘 기억이 안나는데.. 결정했던 것은 없었던걸로 기억합니다!

이 부분에 대해서 금요일날 회의를 해 보는게 나을 것 같습니다.

system 형식으로 갈 지, 프로그램 형식으로 갈 지

**Comment by jongwuner** [comment]
-#1 그냥 아무런 Action을 취하지 않는 시나리오. (가능)
PC방 모델(사용시간이 남아있어도 PC가 켜져있다고 판단)을 따르는 모델은
PC가 자발적으로 꺼졌을 때, client PC 프로세스가 종료된다는 뜻인데, 

long-polling request가 중지됨. 
그러면 서버측에서는 `endTime` 수정되고, 타이머는 여전히 도는데, 
`endTime` 이 되!었!을!때, Error발생.  

+ 수정되어야 하는 사항하나 발생.(@winterlood)
android. 어플켜지고 이후에
- 켜지는 PC에 대한 Get Long-polling 있는데, 
- 꺼지는 PC에 대한 Get Long-polling (???) 추가해야 함. 
  - 이게 생기는 이유는, 안드로이드가 끄라는 명령으로 꺼진 것이 아닌, PC의 종료시나리오로 종료되는 것에 대한 case를 추가해야함.

**Comment by jongwuner** [comment]
# 2) PC Client 프로세스가 종료될 때 POST를 보낸다 (가능)
- 전제 : 항상 Request 중인 상태. (POST, GET)
- 대안 : 서버로 Post를 새로보내서, 기존 스레드를 종료시키고, endTime을 현재(or -1분) 로 바꾼다.

**Comment by damin8** [comment]
2번 계속 개발해보겠습니다

**Comment by winterlood** [comment]
@damin8  
내 기억에도 확실히 PC방 관제 프로그램 처럼,
사용자가 PC를 종료했다 하더라도, 로그아웃이나 사용종료 버튼을 클릭하지 않으면,
시간은 계속 흘러가는 구조로 진행하겠다고 결정된것으로 기억함

@jongwuner 

> 오해가 있을 수 있지만, 내가 이해한 바로 이야기를 해보자면

현재사항 (Android)
---
현재 Android의 Polling은 ~/mobile/pc 의 JSON 데이터를 모두 조회하기 때문에,
꺼지는 PC, 켜지는 PC에 대한 Polling의 구분이 없음
> 그냥 모든 PC의 상태를 주기적으로 갱신하고 있음

궁금중
---
Android측에서, PC의 종료상태를 확인할 수 있는 방법은 Server의 JSON 단 하나뿐임
그러므로 Server에서 JSON이 정상적으로 수정된다면, 
Android는 별도의 long polling이 필요할지 의문
Server가 사용자가 자의적으로 PC를 종료했을 때, 
PowerStatus를 off로 수정한다면 추가적인 GET long polling은 필요 없다고 판단됨

결론
---
즉 이미 모든 PC에 대해 GET 으로 Polling을 진행하고 있으므로,
어떤 변경사항이던, 즉시 알아 차릴 수 있음

**Comment by winterlood** [comment]
추가사항
---
SERVER에서 식별되는 'A' 라는 PC한대가 있다고 가정,
PowerStatus는 'on' 인데, endTime이 현재시간보다 과거일 경우
Android에서는 해당 'A'라는 PC를 종료된 PC라고 간주하도록 수정할까 하는데 의견 바랍니다

**Comment by jongwuner** [comment]
일단 읽고나서 든 생각은
저런경우가 존재할수 없을거같은디?

**Comment by jongwuner** [comment]
혹시 저런 버그가 발생할수도 잇으니, 예방차원에선 좋다고 생각함.
일반적으로는 불가능한 시나리오

**Comment by winterlood** [comment]
혹시 모를 사항을 대비하려 한 의도였는데,
그런 상황이 존재하지 않는다면 땡큐입니다 🤣
