### ISSUE TITLE
PC 종료 (나 언제꺼?) Bug

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#60]
#47 에 있는 나 언제꺼? (PC Shutdown)

#### 1.1. URL로 Post 던지기

![image](https://user-images.githubusercontent.com/52910837/74242410-3106a500-4d21-11ea-8c4f-e4ecf8e6749d.png)

---

#### 1.2. Request 던진 후에 Response 대기

![image](https://user-images.githubusercontent.com/52910837/74241605-ba1cdc80-4d1f-11ea-9613-25c99b1ac4e6.png)

> Long Polling 이기 때문에 응답 대기중

---

#### 1.3. Server의 Log

![image](https://user-images.githubusercontent.com/52910837/74241700-e59fc700-4d1f-11ea-8549-4aea7dd2150a.png)

---

#### 2.1. 10분 전에 알려달라고 요청
 
![image](https://user-images.githubusercontent.com/52910837/74242463-4e3b7380-4d21-11ea-95b2-e4903a3cad2e.png)

> Long-Polling 이라 응답 대기중

#### 2.2. Server의 Log

![image](https://user-images.githubusercontent.com/52910837/74242553-7cb94e80-4d21-11ea-8492-21a7efabe72b.png)

#### 2.3. 10분전에 응답(response) 확인

![image](https://user-images.githubusercontent.com/52910837/74242665-aa9e9300-4d21-11ea-8acf-4359e7d20138.png)

#### 3.1. 지정한 시간(endTime)에 PC 끄기 요청

![image](https://user-images.githubusercontent.com/52910837/74242770-db7ec800-4d21-11ea-810e-52a6be6d3c90.png)

> Android의 Post Long-Polling 이라 response 대기중

#### 3.2. Server의 Log

![image](https://user-images.githubusercontent.com/52910837/74242938-24368100-4d22-11ea-9a62-5098be455be8.png)

#### 4.1. Android의 response

![image](https://user-images.githubusercontent.com/52910837/74242972-32849d00-4d22-11ea-9a3a-c10b497c67ff.png)

> Android Post-Long-polling의 response는 온다.

#### 4.2. PC의 response

![image](https://user-images.githubusercontent.com/52910837/74243065-65c72c00-4d22-11ea-9020-67ee86a12a8f.png)

> 아직도 대기중이다.

## 결론

현재 Android가 끄는 요청 post를 날려서 해당 시간이 되어도, client PC 에게 response가 안 온다.

하지만 Android에게는 status : OFF 로 오게 된다.

따라서 client PC의  "나 언제꺼??" Long polling의 response를 확인해야 할 듯 하다.

**Comment by jongwuner** [comment]
사진 1.3와 같은 현상 해결

**Comment by jongwuner** [comment]
2.1, 2.2, 2.3 해결
3.1 해결

**Comment by jongwuner** [comment]
지금 현재 long-polling 메서드가 동기식으로 작동하여,
가장 마지막에 들어오는 endTime으로 request를 던진 id만 작동하고, 
그 이전에 request는 무한대기로 빠지게됨.

원인 명확히 알았고, 비동기식으로 만들면 해결가능. 
`v1.2.9`에 반영예정. 

20.03.01 06:22에 업로드되어있는건 `v1.2.8`

**Comment by jongwuner** [comment]
`v2.1` 해결
