### ISSUE TITLE
PC 종료 (나 언제꺼?) Bug2

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#61]
#47 에 있는 나 언제꺼? (PC Shutdown)

#### 2.1. 1분 전에 꺼지는 알람 보내달라고 요청

![image](https://user-images.githubusercontent.com/52910837/74243647-7b892100-4d23-11ea-984d-582d51b4b7d1.png)

#### 3.1. 1분전에 알맞은 알람이 온다.

![image](https://user-images.githubusercontent.com/52910837/74243677-8643b600-4d23-11ea-8d48-7b6d40823ae4.png)

### 4. endTime이 되었을 때

![image](https://user-images.githubusercontent.com/52910837/74243819-bee38f80-4d23-11ea-9881-5343019af840.png)

> Post Long-Polling의 응답이 오지 않는다.

## 결론

#60 이랑 같이, Post Long-Pollng의 응답이 오지 않는 것을 보니 Post Long-Polling 쪽을 봐야 할 듯 하다.

**Comment by jongwuner** [comment]
# 60번과 같은 이유로 close
