### ISSUE TITLE
PC 연장 Bug

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#62]
#47 에 있는 PC 연장

#### 1.1. Post Long-Polling URL로 요청 + response 대기

![image](https://user-images.githubusercontent.com/52910837/74245664-b5a7f200-4d26-11ea-9c69-0509dc713228.png)

#### 2.1. Get Long-Polling 5분 전으로 설정 + response 대기

![image](https://user-images.githubusercontent.com/52910837/74245679-be002d00-4d26-11ea-9176-5d8320c744e5.png)

### 3. PC -> Server 연장신청 (One-Time)

![image](https://user-images.githubusercontent.com/52910837/74245699-c5bfd180-4d26-11ea-8266-2ebfd6d46bac.png)

> 이때, 1번과 2번의 response가 와야 하는데 오지 않는다.

![image](https://user-images.githubusercontent.com/52910837/74246545-09ffa180-4d28-11ea-916e-ba77fbad6734.png)

---

## 결론

연장신청을 하면, get, post의 response가 오기로 했었지만 오지 않는다.

**Comment by jongwuner** [comment]
#60 issue와 같은 이유로 close
- 정상적인 시나리오이면 response, request 도착한다.
