### ISSUE TITLE
Spring REST API Server pcs배열 문제 식별

### ISSUE THREAD

**Issue by winterlood** [22hours/system-monitor-study#67]
문제 식별 URL
===
[http://13.125.225.221/mobile/pc](http://13.125.225.221/mobile/pc)

문제 식별 
===
Android Client

문제 원인 
===
PC 전체를 조회하는 GET method 에서 문제가 발생함
![image](https://user-images.githubusercontent.com/46296754/75861029-2206a480-5e40-11ea-991c-6c36ac032e82.png)

살펴보니 다음과 같은 설계와 다른 점이 존재 함

기존 설계 
---
![image](https://user-images.githubusercontent.com/46296754/75860923-f2f03300-5e3f-11ea-8055-90c67ac0a23a.png)

현재 서버 상태
---
![image](https://user-images.githubusercontent.com/46296754/75860886-e2d85380-5e3f-11ea-9eb6-27cd3cd33c9d.png)

차이점
---
기존 설계에서는 pcs 배열의 value는

~~~
pcs : [ {item 1 }. {item 2}. {item 3}] 
~~~

다음과 같았으나, 현재 server에서 확인되는 pcs는 다음과 같은 형태

~~~
pcs : [ "{item 1 }". "{item 2}". "{item 3}" ] 
~~~

따라서 JSON Array 를 읽어오는 과정에서  runtime error 식별되었음

현재
===
Android 상에서 해결 가능한 내용인지 검토중...

요청
===
Server 상에서 원래 설계 구도와 동일하게 변경해 줄 수 있는지 요청

**Comment by jongwuner** [comment]
해결되엇던 이슈.
