### ISSUE TITLE
다소 충격적?인 나의 생각 (PC Client <-> Server)

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#68]
생각을 하고 하고 하고 또 하고

조심스럽게 내 생각을 올려 봅니다.

## PC Client와 Server의 통신 (Client -> Server)

순서대로 

1. 나 언제꺼? (Post Long-Polling)
 - Body에는 각종 정보 들어가 있다.
 - endTime이 되면 Server에서 Response로 끄라고 온다.

2. 나한테 할 말 있어? (Get Long-Polling)
 - 몇 분 전에 알릴껀지?
 - N 분 전이 된다면 Response로 "N분 전입니다! 자료 서둘러 주세요!"
 - 다시 Get 요청

3. data 업데이트 (Post General-Polling 주기적으로 n분마다)
  - Body에는 각종 정보 들어가 있다.
---

## 생각

일단 위에는 프로그램이 실행이 되면 무조건 실행이 되는 부분이다.
 - 사용자가 아무것도 안해도 되어야 하는 부분

우리 통신에 대해서 생각을 하다가

이제와서 **아차!** 싶었던 생각이 들었다.

굉장히 근본적인 생각인데

1번에서 Post Long-Polling 의 Response를 신경써야 하는 이유가 있나? 

이렇게 생각하는 이유

- 우리는 Get 요청으로 몇 분 남았는지 알 수 있다.
- 그렇다면 남은 시간이 0분이라는 뜻은?
- 꺼야 된다는 뜻 (PC Client 에서 처리 해주기)

이렇게 된다면 Post Long-Polling 의 Response를 신경 쓸 필요도 없을 뿐 더러
Server에서 굳이 Request를 붙잡고 있을 필요도 없다.

또, Client 입장에서 Post라면 "어떠어떠한 것을 바꿔줘!" 이다.
그렇다면 Response가 어떻게 오던간에 Post를 던지면 끝이어야 하는게 아닌가?

---

## 결론

PC Client -> Server로 가는 모든 Post 의 response는 null 이 와야 한다고 생각. (붙잡고 있을 필요도 없다)

Get Long-Polling 의 Response에 따라 Client가 처리 하겠습니다.

이 의견에 대한 생각을 부탁드립니다 @jongwuner

**Comment by jongwuner** [comment]
글을 읽고 내가이해한 바로는 일반폴링 Get을 던지자는소리아닌가??

**Comment by winterlood** [comment]
Android 측은 기존 설계와 변동사항 없이 진행하겠습니다 😊

**Comment by damin8** [comment]
음..

내가 생각한 순서는

1. 1회용 Post (모든 데이터 넘겨주기=나 언제꺼?)

-> 1회용 Post이기 때문에 response 필요 x (null 값 받기)

2. Get Long-Polling (나 언제꺼?)

입니다.

그래서 결국에는

Server는 Get 요청에 대해서만 Request를 쥐고 있고

Post 요청은 바로바로 Response를 보내면 되지 않나?

라는 생각입니다.

@jongwuner 

@winterlood  네😊

**Comment by jongwuner** [comment]
그럼
언제꺼? 해서
피씨를 어떻게 끄려고?

**Comment by damin8** [comment]
이게 포인트임

Get Long-Polling의 역할

- 몇 분 남았는지 알려준다

- 클라이언트 측에서 종료시간 0분전에 알려줘~ Request를 던지면

- Server는 Request를 잡고 있다

- 만약 종료시간 0분전이라면? Response를 해주겠지

- Client가 0분전에 알려달라고 했는데 Response가 왔다? = 종료 시간이 되었다는 뜻

- 그러면 Client 입장에서 Response가 왔을 때 처리 해준다면 해결

**Comment by jongwuner** [comment]
기존
Post 1번, Get 1번 던지던 걸

Post 1번, Get 2번

이렇게 바뀌게되지않나?

**Comment by jongwuner** [comment]
기존
Post는 언제꺼 이고, 롱폴링 response

새롭게생각하는것
Post에 즉각 response, 
Get은 메세지 n분전 용 1개, 언제끄는지 알려주는 0분전 용 1개

**Comment by damin8** [comment]
아니지

기존

Post 1번, Get 1번 과 동일

달라지는 점

기존

Post 1번, Get 1번 Response 대기

달라지는 점

Post 1번 바로 Response 받음, Get 1번 Response 기다림

**Comment by jongwuner** [comment]
기존 Get도 대기하는개념인데 머가다른겨?

**Comment by damin8** [comment]
언제끄는지 알려주는 0분전 용 1개는 보낼 필요가 없는게

Client에서 해결해 주면 되는 부분

메세지 n분전 용 1개에서 

n을 0으로 해서 보내면 0분전에 오기 때문에 바로 끄면 돼

**Comment by jongwuner** [comment]
N분전에 받아서 클라에서 n분을 카운트하겟다고?

**Comment by jongwuner** [comment]
이거딱봐도
서버 이슈생겨서 클라에서 일만들어서
해결하려는 방향이구만

**Comment by jongwuner** [comment]
괜찮으니까 그냥 발생한 이슈를 그대로 써줘

**Comment by damin8** [comment]
예시를 들자면

ex) http://13.125.225.221/pc/damin/message/5

이런 url을 보내면 원래 endTime - 5분이 되었을 때 response가 옴

http://13.125.225.221/pc/damin/message/3

보내면 endTime - 3분이 되었을 때 response가 옴

http://13.125.225.221/pc/damin/message/1

보내면 endTime - 1분이 되었을 때 response 가 옴

http://13.125.225.221/pc/damin/message/0

보내면 endTime - 0분 = (끝나는 시간)이 되었을 떄 response 가 옴

---

Client 입장
~~~
if(remainTime == 5)
 remainTime = 3
if(remainTime == 3)
 remainTime = 1
if(remainTime == 1)
 remainTime = 0
if(remainTime == 0)
 컴터 꺼!

Get http://13.125.225.221/pc/damin/message/remainTime
~~~

**Comment by jongwuner** [comment]
일단 너가알아야할 대전제는
Request 1회 = Response 1회야

시스템로그에 저렇게찍는건 가능한데
너가 프록시서버같은게 없는한, 소켓통신이 아닌이상 다량의 메세지는 못보냄.

여기서 메세지는 http통신이기에 response를 말하고

**Comment by jongwuner** [comment]
Http는 response가 피동적이기때문에
Request가 없인 보낼수없서

**Comment by damin8** [comment]
아니아니 알지

Request 1회 = Response 1회

저기에 있는 if문은 response를 해석하는 부분이야

**Comment by jongwuner** [comment]
그런데
어케 request 1개로할수가 잇어

**Comment by jongwuner** [comment]
03시10분에 0350에 끈다고 post를 날리고

Get 은 어떤식으루날려?

**Comment by damin8** [comment]
~~~
public void GetMethod(PC pc) 
			throws URISyntaxException, ClientProtocolException, IOException{
		URI uri = new URI("http://13.125.225.221/pc/damin/message/" + pc.getRemainTime());
		System.out.println(uri);
		HttpClient httpClient = HttpClientBuilder.create().build();
		HttpResponse response = httpClient.execute(new HttpGet(uri));
		HttpEntity entity = response.getEntity();
		String content = EntityUtils.toString(entity);
		System.out.println("Get Long-Polling Response = " + content);
		try {
			JsonElement jsonElement = JsonParser.parseString(content);
			JsonObject jsonObject = jsonElement.getAsJsonObject();
			String id = jsonObject.get("id").getAsString();
			String message = jsonObject.get("msg").getAsString();
			if(jsonObject.get("msg").isJsonNull()) { // PC가 연장 신청 했을 때 혹은 다른 경우
				pc.setRemainTime("30");
			}
			else { // 메시지가 왔을 때 처리
				Thread alarmThread = new AlarmThread(message);
				alarmThread.start();
				if(pc.getRemainTime().equals("30")) {
					pc.setRemainTime("10");
				}
				else if(pc.getRemainTime().equals("10")) {
					pc.setRemainTime("2");
				}
				else if(pc.getRemainTime().equals("5")) {
					pc.setRemainTime("2");
				}
				else if(pc.getRemainTime().equals("2")) {
					pc.setRemainTime("1");
				}
				else if(pc.getRemainTime().equals("1")) {
					pc.setRemainTime("-1");
				}
			}
		}
		catch(Exception e) {
			e.printStackTrace();
		}
~~~

이 코드를 봐봐

이 메서드를 long-polling으로 하는데

response가 오면 다시 request를 보내게 되어 있어

![image](https://user-images.githubusercontent.com/52910837/75953163-22f90e00-5ef4-11ea-9bee-73d14bd22387.png)

**Comment by damin8** [comment]
get은 n분전이라고 날리지

ex) 30분 전
http://13.125.225.221/pc/damin/message/30

이렇게 되면

30분 전에 response가 오겠지?

그럼 remainTime = 15로 바꿔주고

http://13.125.225.221/pc/damin/message/15

로 다시 request를 보내

**Comment by jongwuner** [comment]
그러면 저게 Get이 어케 1번이여
함수가 1번인거지 
함수 1번안에 반복문으로 여러번 req을 보내잖슴

**Comment by jongwuner** [comment]
너가 나한테 결과적으로 던지는 Get의 횟수는 여러번이다 인정?

**Comment by damin8** [comment]
그렇게 보이는데

봐봐 형

Response가 안오면 저 함수가 안끝나.

그럼 뭐다? Long-Polling 이다

**Comment by jongwuner** [comment]
아니 그니까ㅋㅋㅋ 할수잇다고 
그냥 하나의 이슈야

**Comment by jongwuner** [comment]
클라에서 굳이 안해도된다고
Get post호출횟수가 더늘어나기만하는겨

**Comment by jongwuner** [comment]
변경은 어쩌다한번 일어나지만
최소 2번 get 1 post 1
저건 변경이 안일어나도 여러번호출하자나

**Comment by damin8** [comment]
아니아니 원래랑 똑같다니까 형

더 안늘어나!!

원래도 get은 5분전 3분전 하는거고

늘어나는 부분이 아예 없어 형

**Comment by jongwuner** [comment]
아아아아악아니 뭔 개소리야 !!!!!!!!

**Comment by winterlood** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 여기는 댓글창이 아닙니다 ㅠㅠ

**Comment by jongwuner** [comment]
안드로이드와 PC, 서버구조가 다바뀌는 1타3피의 문제가 갑자기 발생하므로 
좋은 구조지만 추후로 Delay합니다.
