### ISSUE TITLE
PC Extension Error

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#69]
1. Post (나 언제꺼?)

- 50분에 끄는거야~

![image](https://user-images.githubusercontent.com/52910837/75982845-ccf38d00-5f2a-11ea-84c4-4743574861f0.png)

2. Get (나한테 할 말 있어?)

- 1분전에 알려줘

![image](https://user-images.githubusercontent.com/52910837/75982865-d54bc800-5f2a-11ea-9d5e-71b56ed92da1.png)

3. Post (연장신청)

- 나 52분으로 연장할래~

![image](https://user-images.githubusercontent.com/52910837/75983056-1d6aea80-5f2b-11ea-9cc1-92e0d3a01358.png)

4. Post (나 언제꺼?)

- 50분에 끄는거 Response (powerStatus : ON) 으로 제대로 온다.

![image](https://user-images.githubusercontent.com/52910837/75982886-de3c9980-5f2a-11ea-918f-bd6bd046dc08.png)

5. Get (나한테 할 말 있어?)

- Response가 안온다.

- 원래대로라면 null 값으로 Response가 와서 다시 요청해야 함.

![image](https://user-images.githubusercontent.com/52910837/75982908-e4cb1100-5f2a-11ea-8045-04e3a4bb98e0.png)

---

# 결론

연장신청 했을 때

원래대로라면 Post(나 언제꺼?) 와 Get(나한테 할 말 있어?)가 둘 다 Response가 와야 한다.

현재는

Get (나한테 할 말 있어?) 의 Response가 와야 하는데 오지 않는다

둘 중 Post만 온다.

**Comment by jongwuner** [comment]
## 해결
연장(변경)신청 하면 long-polling 중이던 msg를 즉시 반환 (null). 

## Test 결과
------------------------ POST, GET 1회씩, POST 연장으로 수정 ---------------------------

19-40 (GET) v 43
19-42 (POST) v 안와야함.  <------ 이시간에 GET이 옴.

19-45 post 변경 <- O

------------------------ POST, GET 1회씩, POST 연장으로 수정 ---------------------------

20-10 (GET) 5분전 v 안와야 함. <-- 안왔음!
20-15 (POST) v 안와야함.  - 이시간에 GET이 옴. 

20-17 (수정) GET와야함.
20-22 (수정) post 변경 와야함.


------------------------ POST, GET 1회씩, POST 단축으로 수정 ---------------------------
