### ISSUE TITLE
(UI) Android Cpu PC인스턴스 게이지바 

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#72]
![image](https://user-images.githubusercontent.com/16419202/76146188-159a7a00-60d4-11ea-8103-9600338d75bd.png)

숫자만큼 게이지바가 반영되지 않고 있음.

**Comment by winterlood** [comment]
원인 
---
SERVER에서 제공하는 RAM, CPU Data의 Format을 잘못 인지하여 
NumberFormatException 이 일어나고 있었음 
> 무분별한 Try Catch 남발로 인지 못하고 있었던 버그

즉 Server에서 제공하는 CPU사용량이 6.20 이라면 
6.20은 Int형이 아니므로 Int형 Value를 갖는 프로그레스바(소위 게이지바)에 대입할 경우 
예외를 내뿜고 있었음

변경
---
![image](https://user-images.githubusercontent.com/46296754/76153810-e6582d00-6114-11ea-9eef-30e6e66b29f7.png)

프로그레스바(게이지바)에 적용되는 Value값에,
SERVER에서 제공하는 RAM,CPU 사용량의 소수점 이하의 자리는 버리고 정수만 취하기로 했음

따라서, 주어진 문자열을 **.** 을 기준으로 split하여 0번 인덱스에 해당하는 값 (소수의 정수부)만
게이지바의 value로 반영하기로 결정하여 해결

해결
---
![image](https://user-images.githubusercontent.com/46296754/76153783-94afa280-6114-11ea-830d-e1129b010e5d.png)
