### ISSUE TITLE
(UI) PC가 리스트에서 ON/OFF별로 보여지는 UI의 차이가 없음.

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#73]
![image](https://user-images.githubusercontent.com/16419202/76146486-64491380-60d6-11ea-8195-3f29729cab0f.png)

- 모두 회색빛이고, 
- OFF 상태인 PC는 클릭하면 `종료되었습니다.` 라는 메세지
- ON 상태이면, 인스턴스 자세히 보는 창으로 이동. 
- 원래 ON이면 파란색 테투리로 바뀌지 않나?

**Comment by winterlood** [comment]
오류 발생 원인
---
![image](https://user-images.githubusercontent.com/46296754/76153680-8f515880-6112-11ea-9b22-4f86f964c5fb.png)

위 처럼 조건문이 참이 되는 경우는 "on" 이였으므로 해당 버그발생

수정 사항
---
![image](https://user-images.githubusercontent.com/46296754/76153692-c162ba80-6112-11ea-816e-0d65be51bc02.png)

"ON" 도 동일하게 반영

결과 
---
![image](https://user-images.githubusercontent.com/46296754/76153699-cf184000-6112-11ea-887a-c2becd3acdee.png)
