### ISSUE TITLE
(Front) 어플이 켜져있는 상태에서 종료시간이 되었을때 여전히 인스턴스창이 들어가짐.

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#74]
![image](https://user-images.githubusercontent.com/16419202/76146504-9ce8ed00-60d6-11ea-82f5-da958ee0d1cf.png)

- 어플이 계속 Polling 유지하면서 대기 중인 상태에서, 종료시간이 되었고(Server 상으로 Response확인했음.)
- PC종료가 되지 않고 켜져있는 상태로 남아있음.

**Comment by winterlood** [comment]
원인
---
변수이름을 잘못씀
> 두 글자 차이로 세개의 기능이 고장난 희대의 실수

해결
---
![issue74solve](https://user-images.githubusercontent.com/46296754/76154039-fa9e2900-6118-11ea-9f75-26e3d6b43026.gif)
