### ISSUE TITLE
(Front) Class 분류 아직?

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#75]
![image](https://user-images.githubusercontent.com/16419202/76146548-f9e4a300-60d6-11ea-89db-95ba8edad781.png)

- ClassId별 인스턴스 cnt가 안되고 있음.

**Comment by winterlood** [comment]
원인
---
기능 구현이 안되어있었네용 ... 😂

해결
---
![image](https://user-images.githubusercontent.com/46296754/76154261-a6954380-611c-11ea-8fc1-8bc8b9506fb3.png)
