### ISSUE TITLE
(Front) Mobile 셧다운 에러

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#76]
## 1. 셧다운 시(지금현재 '즉시종료'기능 기준), 
 DB상에 PowerStatus OFF로는 변환하는데, endTime에 수정이 안되서 반영되는 중

----------------------------------------------------------------------------------------------
## 2.  셧다운 시, 켜져있다는 표시(파란색테두리)가 사라자지 않음.

![image](https://user-images.githubusercontent.com/16419202/76158023-a3b64500-6154-11ea-8d34-819aae362b52.png)

---------------------------------------------------------------------------------------------
### 3. DB상에 설정되어있는 endTime이 되었을 때, 어플에서 이 PC가 꺼졌다는 전환을 해주지 않음.

![image](https://user-images.githubusercontent.com/16419202/76158004-5043f700-6154-11ea-9ee4-ef220d956b75.png)
> powerStatus : ON, endTime : 2020-03-08-15-41  // 캡쳐시간 2020-03-08-15-49

**Comment by jongwuner** [comment]
가독성 ㅎㅌㅊ처럼 써놧지만, 에러가 3가지

**Comment by winterlood** [comment]
3번 Issue에 대하여 
현재 Android는 PC의 on/off를 다음과 같은 우선순위로 확인함
1. Server에 명시되어있는 PowerStatus
2. endTime 
위 3번 issue의 경우 endTime은 지나갔지만 Server에서 PowerStatus를 on이라고 설정해놓았기에,
켜져있다고 판별되는것으로 보임

**Comment by jongwuner** [comment]
URL 잘못들어가있었으나 해결!
