### ISSUE TITLE
(Front) Mobile DB 수정할때 중복인스턴스 생성

### ISSUE THREAD

**Issue by jongwuner** [22hours/system-monitor-study#77]
![image](https://user-images.githubusercontent.com/16419202/76158059-f5f76600-6154-11ea-992a-f5fb65a811e2.png)

- POST를 통해 Client상에서 연장신청을 하게 될 경우, 안드로이드에서는 중복인스턴스가 생긴것 처럼
 작동.
- Class 별 View에서는 제대로 카운트됌.(중복인스턴스 숫자를 세진 않음)
- 어플 재접속하면 중복인스턴스 사라짐.
- v0.1에서부터 있었던 문제인데, 긴가민가해서 언급하진 않았고, 개선된 환경에서 다시 테스트해보니 분명하게 식별됨

**Comment by winterlood** [comment]
Android 상에서, pc를 id별로 구분하므로, id가 중복되는 pc가 존재하면, 문제가 발생하는듯 함

**Comment by jongwuner** [comment]
## ID다 DB key값으로 변경하고, 중복없는 상황에서도 동일한 증상 발생.
- 수정되는 사항이 기존 인스턴스를 덮어쓰지 않고, 생성해둠.
- 어플 재접속 시, 기존꺼 사라짐.

![image](https://user-images.githubusercontent.com/16419202/76158228-06104500-6157-11ea-8b5d-bf398f3062bf.png)
> Before (어플 재접속 전)
![image](https://user-images.githubusercontent.com/16419202/76158241-1cb69c00-6157-11ea-8984-99c563d98e67.png)
> After (어플 재접속 후)

**Comment by winterlood** [comment]
![issue77](https://user-images.githubusercontent.com/46296754/76158813-3c50c300-615d-11ea-8724-cd30fb3b49e1.gif)

문제 발생 원인 
-> on된 instance의 endTime을 연장신청 할 시 중복 인스턴스가 생성된다는 걸로 인지

흐음 내 핸드폰과 android emulator에서는 다음과 같이  정상적으로 동작함 이유가 뭐지 ?

**Comment by winterlood** [comment]
@jongwuner  문제발생 gif 첨부 가능한지
