### ISSUE TITLE
(Android) PC endTime delay(종료시간 연장신청) 시,  24시 이후 다음 날짜로 넘어가지 않음 

### ISSUE THREAD

**Issue by winterlood** [22hours/system-monitor-study#79]
최대한 빠르게 수정 예정

**Comment by winterlood** [comment]
![image](https://user-images.githubusercontent.com/46296754/76695291-ec27b280-66c0-11ea-9e73-5397d225d92d.png)

**Comment by jongwuner** [comment]
저거 숫자 
yyyy-mm-dd-hh-mm
로 수정되야함

2020-04-01-00-15

**Comment by winterlood** [comment]
yyyy-mm-dd-hh-mm 혹시 어떤 자료형 패턴인지 알수있음 ??

**Comment by jongwuner** [comment]
String

**Comment by winterlood** [comment]
yyyy-mm-dd hh:mm:ss 사용하지 않는 이유가 특별히 있나 ??

**Comment by jongwuner** [comment]
URL로 던져주기위함

**Comment by winterlood** [comment]
ㅇㅋㅇㅋ

2020년 3월 15일 (일) 오후 1:32, 이종원 <notifications@github.com>님이 작성:
