### ISSUE TITLE
사용자가 우리 프로그램 끌 때 (PC)

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#81]
3가지 방안?이 있습니다.

1. 우리 프로그램을 끌 때 사용자에게

~~~
이 프로그램을 끈다면 컴퓨터가 꺼집니다.
그래도 괜찮으시겠습니까?

yes or no
~~~

이런식으로 사용자가 우리 프로그램을 끈다? 

= 컴퓨터 꺼버리기

2. 사용자가 프로그램을 끄면 아무 신경 안쓰기

굉장히 불편할 것으로 예상

3. 사용자가 프로그램 끄면 자동적으로 다시 프로그램을 system에서 켜기

---

무엇이 좋으십니까?!

@jongwuner @winterlood

**Comment by jongwuner** [comment]
1번이 제일좋은데, 오류로 프로그램이 튕기면 답이없네.

너가 주도해서 하겟지만, 가장중요한건
어떠한 순간에도 프로세스가 돌고잇어야함
일단 컴터가 틀어지면 자동으로 실행도 돼야하고

**Comment by jongwuner** [comment]
Shutdown Hook으로 Post를 보낸다!
