### ISSUE TITLE
안드로이드 어플리케이션 프로세스 사용 중 아닐 시 Polling 중단,

### ISSUE THREAD

**Issue by winterlood** [22hours/system-monitor-study#83]

**Comment by winterlood** [comment]
> _No description provided._

ㅇㅇ

**Comment by jongwuner** [comment]
![image](https://user-images.githubusercontent.com/16419202/77827209-ae626980-7157-11ea-97d2-b32f2789e50d.png)

지속적으로 Polling 요청이 오고있음.

**Comment by winterlood** [comment]
React에서 해결된 사항
