### ISSUE TITLE
PC Client 연장 신청

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#84]
- 18시 40분으로 종료시간 Post

![image](https://user-images.githubusercontent.com/52910837/77409686-0407e080-6dfd-11ea-81d0-f77f59a1be25.png)

- 5분전에 알려달라고 Get

![image](https://user-images.githubusercontent.com/52910837/77409713-11bd6600-6dfd-11ea-89aa-c00b3879e279.png)

- PC 연장 신청 (18시 50분으로)

![image](https://user-images.githubusercontent.com/52910837/77409750-213caf00-6dfd-11ea-81f1-91b5b42838c4.png)

- 원래 있던 Post (18시 40분) 응답 메시지

- 상관 없긴 한데 이런식으로 메시지가 옵니다

![image](https://user-images.githubusercontent.com/52910837/77409765-27cb2680-6dfd-11ea-8536-7a5af4a7e51a.png)

- 연장신청 하면 (message = "null") 로 오기로 했었는데 (message = "OFF") 로 옵니다.

- 문제 발생 ( 끄는 상황인지, 연장 인지 구분이 안가는 상황)

![image](https://user-images.githubusercontent.com/52910837/77409782-2e599e00-6dfd-11ea-8e75-87ff8bfd7a6a.png)

**Comment by jongwuner** [comment]
Off로 달라햇자나 다민

**Comment by jongwuner** [comment]
오잉 response 저거 redis 연동잘 안된다는 에러인데, 다른건 잘돼나?

**Comment by damin8** [comment]
그랬었나?! 내 기억상으로 OFF는 끄는거니까 다른거(msg?? or null??)나 형이 정해서 알려달라고 했던거 같은데

만약 아니라면 다른 문자로 바꿔야 할 듯 해 형

**Comment by damin8** [comment]
저 response 받고 시간 기다려본 결과 endTime 됐을 때 response가 정상적으로 와

**Comment by jongwuner** [comment]
Null이엇는데 Off로 바꺼달라해서 일부러바꾼겁니당

**Comment by jongwuner** [comment]
Response 이상하네 저건 다시 확인해볼게

**Comment by damin8** [comment]
오케오케

연장신청 문자는 OFF말고 다른걸로 하자 형

끄는 상황인지 연장 상황인지 구분이 안가서

**Comment by jongwuner** [comment]
아랏다 몰로바꺼

**Comment by damin8** [comment]
msg="extension"

소문자로!

**Comment by jongwuner** [comment]
ㅇㅋㅇㅋ 바꿀겡

**Comment by jongwuner** [comment]
Unable to Connect 는 서버로그에서 Connection.Exit 확인.

**Comment by jongwuner** [comment]
PC에서 PC extension을 수행할 때, `Thread.getName()` 을 활용해서, 기존에 있던 Thread가 수행중이면 stop 시키고, 수행하고나서 이름부여(추후에 thread 중지시킬 수 있도록)
