### ISSUE TITLE
PC 일반 폴링 <-> Server 오류

### ISSUE THREAD

**Issue by damin8** [22hours/system-monitor-study#89]
![image](https://user-images.githubusercontent.com/52910837/78799318-edfd4100-79f4-11ea-80c1-e4af80e7a129.png)

![image](https://user-images.githubusercontent.com/52910837/78799380-01a8a780-79f5-11ea-9018-fde9b5f8cd8d.png)

- 5분마다 변경해주는 cpu, ram data 사용량

- postman으로 url 던진 결과 404 error

**Comment by jongwuner** [comment]
빌드 간 발생했던 실수로 해결되었음.!
