### ISSUE TITLE
[SERVER] POST로 수정된 PC instance가 속하는 CLASS 조회 시 internal server error (500)

### ISSUE THREAD

**Issue by winterlood** [22hours/system-monitor-study#93]
문제
---
POST로 생성된 PC에 대하여,
해당 PC가 속하는 Class를 GET하는데 문제가 발생함
>ex ) id: king, classId : D405로 pc를 생성하게 되면 D405 class에 대한 정보를 얻어 올 수 없음

설명
---
![image](https://user-images.githubusercontent.com/46296754/79557936-60011480-80de-11ea-8c87-9cbd99037655.png)

잘 실행되고 있는
~~~
GET :  ~/mobile/class/D405
~~~
![image](https://user-images.githubusercontent.com/46296754/79558068-9179e000-80de-11ea-8e5f-0a6454f96b5e.png)

다음과 같은 POST 수행
~~~
POST : ~/pc/king/data
~~~
> king 이라는 pc를 만듦

![image](https://user-images.githubusercontent.com/46296754/79558151-af474500-80de-11ea-8073-1ef35bc077e4.png)

다음과 같이 POST는 잘 수행 되었음

![image](https://user-images.githubusercontent.com/46296754/79558301-e289d400-80de-11ea-8e6f-1dc94ab906ec.png)

> POST 반영은 문제 없음

![image](https://user-images.githubusercontent.com/46296754/79558368-fdf4df00-80de-11ea-9c51-21559f2d554e.png)

그러나, POST로 수정한  king이라는 pc가 속하는 class인

D405는 이제 GET 조회시 Internal Server Error가 발생하게 된다.

~~~
GET :  ~/mobile/class/D405

~~~

**Comment by winterlood** [comment]
[#92](https://github.com/22hours/system-monitor-study/issues/92) 와  연관이 있는건가

**Comment by jongwuner** [comment]
해결입니다.
`POST ~/pc/{id}/data` 로 생성되던 Data에 누락된 key가 있어서 
컴파일오류였습니다.
