### ISSUE TITLE
[SERVER] 새로운 PC Instacne 추가 POST 수행 시, ~/mobile로 시작하는 모든 엔드포인트 500에러

### ISSUE THREAD

**Issue by winterlood** [22hours/system-monitor-study#96]
문제 상황
---
![image](https://user-images.githubusercontent.com/46296754/79955669-120f5680-84ba-11ea-9e37-05e6a02815a9.png)

![image](https://user-images.githubusercontent.com/46296754/79955685-19366480-84ba-11ea-90d7-c787792d695c.png)

문제 발생 원인
---

PC Client에서, ~/pc/{pcId}/data 로 POST 수행 시,

REACT가 조회하는 엔드포인트 전체 마비가 일어남, 
~~~
mobile/ ( 모두 )
~~~

**Comment by jongwuner** [comment]
데이터 추가 잘못해서 그렇슴.
key는 11개임.
데이터 추가가 잘못되는 시나리오는 개발자들이 테스트 하는 과정에서만 생기므로 일단 신경안썼던 부분이긴 한데, 이를 방지하기 위해 error 메세지의 시나리오를 짜서 추가할 계획입니다
